# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

image: Previous Visual Studio 2019

branches:
  only:
    - master

version: 0.0.1.{build}

init:
  - git config --global core.autocrlf false

build_script:
  - cmd: >-
      dotnet tool restore
      dotnet fake build

test_script:
  - dotnet fake build -t Test