name: CI

on: [push, pull_request]

jobs:
  build:

    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest, macOS-latest]
        os: [ubuntu-latest, windows-latest]
        dotnet: [3.1.201]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@master
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}

    - name: Build
      run: |
        dotnet tool restore
        dotnet paket restore
        dotnet fake build
      env:
        CI: true

    - name: Test
      run: dotnet fake build -t Test
